### ISSUE TITLE
Allow alternate keys

### ISSUE THREAD

**Issue by JoeStrout** [treytomes/micro-hack#35]
For example, select should allow both 10 (enter) and 13 (return); exit should allow both 27 (esc) and 96 (back tick, for keyboards like my iPad keyboard that lack an Esc key!).

Suggested API would be, in keybindings.ms, allow a list instead of a number.  Then accept any key code in the list as indicating that function.

**Comment by treytomes** [comment]
I think that would be relatively easy to implement.

**Comment by treytomes** [comment]
This will be available on the next merge to main.
